version: "3.10"
networks:
  proxy:
    external: true

services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    ports:
      - "5009:5009"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
      # local database for testing
      DB_VENDOR: "h2"
      KC_FEATURES: admin-fine-grained-authz
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_HTTP_ENABLED: "true"
      # set port to 5009
      KC_HTTP_PORT: "5009"
    networks:
      - proxy
    volumes:
      - ./local-dev-env/keycloak:/opt/keycloak/data/import
    command: start-dev --import-realm
