version: '3.8'

networks:
  authentik-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1

services:
  authentik:
    image: ghcr.io/goauthentik/server:${AUTHENTIK_TAG:-2023.10.6}
    container_name: oidc
    hostname: oidc
    command: server
    environment:
      #AUTHENTIK_LISTEN__HTTP: 0.0.0.0:8082
      AUTHENTIK_DISABLE_UPDATE_CHECK: true
      AUTHENTIK_BOOTSTRAP_PASSWORD: ${AUTHENTIK_BOOTSTRAP_PASSWORD:-iamastupidtest}
      AUTHENTIK_BOOTSTRAP_TOKEN: ${AUTHENTIK_BOOTSTRAP_TOKEN:-w73e89rf23uioqhezrgd793qgifweurfhgq}
      AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
      AUTHENTIK_POSTGRESQL__USER: ${POSTGRES_DATABASE:-medlog}
      AUTHENTIK_POSTGRESQL__NAME: ${POSTGRES_DATABASE:-medlog}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${POSTGRES_PASSWORD:-w789efhweds3rt43wredfwf}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:-CHANGE_ME_FOR_GODS_SAKE_s89dtzfgo42wuhrf083qrhgfewuoasdfghouesdhfkjsd}
      AUTHENTIK_LOG_LEVEL: debug
    volumes:
      - ./medlog-demo-data/oidc/authentik/media:/media
      - ./medlog-demo-data/oidc/authentik/custom-templates:/templates
      - ./provisioning/authentik:/blueprints/custom
    ports:
      - 9000:9000
    networks:
      authentik-net:
        ipv4_address: 172.25.0.12

  authentik-worker:
    image: ghcr.io/goauthentik/server:${AUTHENTIK_TAG:-2023.10.6}
    command: worker
    environment:
      #AUTHENTIK_LISTEN__HTTP: 0.0.0.0:9000
      AUTHENTIK_DISABLE_UPDATE_CHECK: true
      AUTHENTIK_BOOTSTRAP_PASSWORD: ${AUTHENTIK_BOOTSTRAP_PASSWORD:-iamastupidtest}
      AUTHENTIK_BOOTSTRAP_TOKEN: ${AUTHENTIK_BOOTSTRAP_TOKEN:-w73e89rf23uioqhezrgd793qgifweurfhgq}
      AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
      AUTHENTIK_POSTGRESQL__USER: ${POSTGRES_DATABASE:-medlog}
      AUTHENTIK_POSTGRESQL__NAME: ${POSTGRES_DATABASE:-medlog}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${POSTGRES_PASSWORD:-w789efhweds3rt43wredfwf}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY:-CHANGE_ME_FOR_GODS_SAKE_s89dtzfgo42wuhrf083qrhgfewuoasdfghouesdhfkjsd}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./medlog-demo-data/oidc/authentik/media:/media
      - ./medlog-demo-data/oidc/authentik/custom-templates:/templates
      - ./provisioning/authentik:/blueprints/custom
    networks:
      authentik-net:
        ipv4_address: 172.25.0.13

  authentik-postgresql:
    image: docker.io/library/postgres:12-alpine
    restart: unless-stopped
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U ${POSTGRES_DATABASE:-medlog}"
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./medlog-demo-data/oidc/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-w789efhweds3rt43wredfwf}
      - POSTGRES_USER=${POSTGRES_DATABASE:-medlog}
      - POSTGRES_DB=${POSTGRES_DATABASE:-medlog}
    networks:
      authentik-net:
        ipv4_address: 172.25.0.14

  authentik-redis:
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    restart: unless-stopped
    volumes:
      - ./medlog-demo-data/oidc/cache:/data
    networks:
      authentik-net:
        ipv4_address: 172.25.0.15
