name: Docker Image CI
on: [push]


jobs:


build:


runs-on: ubuntu-latest
env:
PG_PASS: ${{ secrets.PG_PASS }}
AUTHENTIK_SECRET_KEY: ${{ secrets.PG_PASS }}


steps:



uses: actions/checkout@v1

name: Build the docker-compose stack
run: docker-compose up -d


name: Check running containers
run: docker ps

name: Run test suite
run: docker exec backend pytest --skip-auth
